### ISSUE TITLE
Vraag in CSS

### ISSUE THREAD

**Issue by JeroenHeemskerk** [uknowwho/educom-webshop-basis-1712050575#13]
Het antwoord op deze vraag
https://github.com/uknowwho/educom-webshop-basis-1712050575/blob/57ac1573831da3e93bc0b34396baeb2f0dc12347/styles.css#L40-L43
Moet denk ik "Ja" zijn, want je wilt als een link in de content wordt aangeklikt dat de kleur niet paars wordt.

**Comment by uknowwho** [comment]
Dank, dus de .content selector "herhaalt" zich niet.
