### ISSUE TITLE
Deze code is specifiek voor de pagina's, misschien een functie maken in om de header op te halen

### ISSUE THREAD

**Issue by JeroenHeemskerk** [uknowwho/educom-webshop-basis-1712050575#15]
De code hieronder bevat pagina specifieke zaken,
https://github.com/uknowwho/educom-webshop-basis-1712050575/blob/a9130c5254b22e4a48b889d53317a08b59f19795/index.php#L42-L51

Misschien handig om in contact.php een showContactHeader te maken die dan de tekst "Contact" teruggeeft

Deze header kan je dan ook hier gebruiken:
https://github.com/uknowwho/educom-webshop-basis-1712050575/blob/a9130c5254b22e4a48b889d53317a08b59f19795/index.php#L62-L64
Om in plaats van Formulierensite de naam van de pagina te tonen.

**Comment by JeroenHeemskerk** [comment]
Ik zou de `<title>` VOOR de switch-case echo-en en de `<\title>` NA de switch-case

**Comment by uknowwho** [comment]
Ik gebruik de "Formulierensite" als een soort banner/logo.  Ik heb de showHeader() functie wel aangepast zoals gevraagd (via functies in betreffende pagina.php bestanden).
